### ISSUE TITLE
OAuth flow bug causes insertion failures

### ISSUE THREAD

**Issue by juliaschatz** [juliaschatz/onshape-library-window#50]
Was able to replicate once on Chrome under enhanced privacy mode, but appears to be very state-dependent and only happens in specific ill-defined scenarios that make reproduction difficult.
```
May 22 05:33:41 curie www[819]: GET /application/?type=assem&docId=58658e04ab2a45091563c561&wvm=w&wvmId=40862633a6b99b571449386d&eId=e9e8f055642923ad758ef973&companyId=cad&server=https%3A%2F%2Fcad.onshape.com&userId=594c79edaaa6ce0f2f99>
May 22 05:33:42 curie www[815]: GET /static/css/main.8bbdaa38.chunk.css 200 0.998 ms - 170
May 22 05:33:42 curie www[820]: GET /static/js/2.d0e6ceae.chunk.js 200 1.291 ms - 422861
May 22 05:33:42 curie www[817]: GET /static/js/main.cf460107.chunk.js 200 1.983 ms - 30291
May 22 05:33:42 curie www[815]: GET /api/isAdmin 500 6.935 ms - 183
May 22 05:33:42 curie www[817]: GET /oauthSignin?redirectOnshapeUri=https%3A%2F%2Fmkcad.julias.ch%2Fapplication%2F%3Ftype%3Dassem%26docId%3D58658e04ab2a45091563c561%26wvm%3Dw%26wvmId%3D40862633a6b99b571449386d%26eId%3De9e8f055642923ad75>
May 22 05:33:42 curie www[820]: GET /api/mkcadDocs 200 25.599 ms - 1975
May 22 05:33:42 curie www[819]: GET /api/data?bust=0 200 205.556 ms - 2684985
May 22 05:33:45 curie www[819]: GET /oauthRedirect?code=MnoyTKOVAorrrQGhbYVnUVdq 302 304.133 ms - 128
May 22 05:33:45 curie www[815]: GET /application?code=MnoyTKOVAorrrQGhbYVnUVdq 301 1.138 ms - 249
May 22 05:33:45 curie www[820]: GET /application/?code=MnoyTKOVAorrrQGhbYVnUVdq 200 0.705 ms - 2968
May 22 05:33:46 curie www[819]: GET /api/isAdmin 200 151.244 ms - 13
May 22 05:33:46 curie www[817]: GET /api/data?bust=0 200 179.236 ms - 2684985
May 22 05:34:03 curie www[815]: CATCH 404
May 22 05:34:03 curie www[815]: Error:  404
May 22 05:34:03 curie www[815]: (node:815) UnhandledPromiseRejectionWarning: StatusCodeError: 404 - [object Object]
May 22 05:34:03 curie www[815]:     at new StatusCodeError (/home/julia/mkcad_parts/node_modules/request-promise/lib/errors.js:26:15)
May 22 05:34:03 curie www[815]:     at Request.RP$callback [as _callback] (/home/julia/mkcad_parts/node_modules/request-promise/lib/rp.js:64:32)
May 22 05:34:03 curie www[815]:     at Request.self.callback (/home/julia/mkcad_parts/node_modules/request/request.js:185:22)
May 22 05:34:03 curie www[815]:     at Request.emit (events.js:198:13)
May 22 05:34:03 curie www[815]:     at Request.<anonymous> (/home/julia/mkcad_parts/node_modules/request/request.js:1154:10)
May 22 05:34:03 curie www[815]:     at Request.emit (events.js:198:13)
May 22 05:34:03 curie www[815]:     at IncomingMessage.<anonymous> (/home/julia/mkcad_parts/node_modules/request/request.js:1076:12)
May 22 05:34:03 curie www[815]:     at Object.onceWrapper (events.js:286:20)
May 22 05:34:03 curie www[815]:     at IncomingMessage.emit (events.js:203:15)
May 22 05:34:03 curie www[815]:     at endReadableNT (_stream_readable.js:1145:12)
May 22 05:34:03 curie www[815]:     at process._tickCallback (internal/process/next_tick.js:63:19)
May 22 05:34:03 curie www[815]: (node:815) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was no>
May 22 05:34:03 curie www[815]: (node:815) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
May 22 05:34:03 curie www[815]: POST /api/insert?documentId=null&workspaceId=null&elementId=null 200 126.764 ms - -```

**Comment by juliaschatz** [comment]
Possible fix: instead of storing redirect URL in redis, store in cookie.
